// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTtVn1r2UuDjZvKV6qmvV1cmEMe9_GWTI',
    appId: '1:978242652882:web:8231d463314082382c3b0b',
    messagingSenderId: '978242652882',
    projectId: 'projectr-a99a2',
    authDomain: 'projectr-a99a2.firebaseapp.com',
    storageBucket: 'projectr-a99a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArx_vtaxEXFAbjJSetrs63gpK3D5EeKwg',
    appId: '1:978242652882:android:4172192a6be99e742c3b0b',
    messagingSenderId: '978242652882',
    projectId: 'projectr-a99a2',
    storageBucket: 'projectr-a99a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBa53Uc3_hLjEMRg6z1r2lV85yK9jmjM',
    appId: '1:978242652882:ios:fb5b7cf1bcbcab462c3b0b',
    messagingSenderId: '978242652882',
    projectId: 'projectr-a99a2',
    storageBucket: 'projectr-a99a2.firebasestorage.app',
    iosBundleId: 'com.example.readifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeBa53Uc3_hLjEMRg6z1r2lV85yK9jmjM',
    appId: '1:978242652882:ios:fb5b7cf1bcbcab462c3b0b',
    messagingSenderId: '978242652882',
    projectId: 'projectr-a99a2',
    storageBucket: 'projectr-a99a2.firebasestorage.app',
    iosBundleId: 'com.example.readifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTtVn1r2UuDjZvKV6qmvV1cmEMe9_GWTI',
    appId: '1:978242652882:web:73e3cfbb7bfeb4352c3b0b',
    messagingSenderId: '978242652882',
    projectId: 'projectr-a99a2',
    authDomain: 'projectr-a99a2.firebaseapp.com',
    storageBucket: 'projectr-a99a2.firebasestorage.app',
  );
}
